export const colorList = [
  "#F87171", // Stronger Soft Red
  "#FB923C", // Stronger Soft Orange
  "#FACC15", // Stronger Soft Yellow
  "#A3E635", // Stronger Soft Lime
  "#4ADE80", // Stronger Soft Green
  "#34D399", // Stronger Soft Emerald
  "#2DD4BF", // Stronger Soft Teal
  "#22D3EE", // Stronger Soft Cyan
  "#38BDF8", // Stronger Soft Sky
  "#60A5FA", // Stronger Soft Blue
  "#818CF8", // Stronger Soft Indigo
  "#A78BFA", // Stronger Soft Violet
  "#C084FC", // Stronger Soft Purple
  "#E879F9", // Stronger Soft Fuchsia
  "#F472B6", // Stronger Soft Pink
  "#FB7185", // Stronger Soft Rose
  "#A8A29E", // Stronger Soft Stone
  "#FBBF24", // Stronger Soft Amber
];
